import { LanguageCode } from '../types';

export const getCaregiverModalStrings = (lang: LanguageCode) => {
  const dict: Record<LanguageCode, {
    title: string;
    pinTitle: string;
    pinSub: string;
    defaultPinHint: string;
    photosTab: string;
    remindersTab: string;
    notesTab: string;
    syncTab: string;
    exitBtn: string;
    addPhoto: string;
    addReminder: string;
    saveNotes: string;
    notesPlaceholder: string;
  }> = {
    as: {
      title: 'সেৱাদানকাৰী মোড',
      pinTitle: 'সুৰক্ষা পিন (PIN) দিয়ক',
      pinSub: 'পৰিয়াল আৰু চিকিৎসা তথ্য সুৰক্ষিত ৰাখিবলৈ ৪-অংকৰ পিন দিয়ক',
      defaultPinHint: 'ডিফল্ট পিন: 1 2 3 4',
      photosTab: 'ছবি ব্যৱস্থাপনা',
      remindersTab: 'স্মাৰক তালিকা',
      notesTab: 'স্বাস্থ্য টোকা',
      syncTab: 'ক্লাউড চিনক্ৰনকৰণ',
      exitBtn: 'সেৱাদানকাৰী মোড ত্যাগ কৰক',
      addPhoto: '+ নতুন স্মৃতিৰ ছবি দিয়ক',
      addReminder: '+ নতুন স্মাৰক যোগ কৰক',
      saveNotes: 'টোকা সংৰক্ষণ কৰক',
      notesPlaceholder: 'চিকিৎসকৰ পৰামৰ্শ, ৰক্তচাপৰ তথ্য বা বিশেষ নিৰ্দেশনা ইয়াত লিখক...',
    },
    hi: {
      title: 'केयरगिवर मोड',
      pinTitle: 'सुरक्षा पिन (PIN) दर्ज करें',
      pinSub: 'परिवार और स्वास्थ्य विवरण सुरक्षित रखने के लिए 4 अंकों का पिन दर्ज करें',
      defaultPinHint: 'डिफ़ॉल्ट पिन: 1 2 3 4',
      photosTab: 'फ़ोटो प्रबंधन',
      remindersTab: 'रिमाइंडर सूची',
      notesTab: 'स्वास्थ्य नोट्स',
      syncTab: 'क्लाउड सिंक',
      exitBtn: 'केयरगिवर मोड से बाहर निकलें',
      addPhoto: '+ नई स्मृति फ़ोटो जोड़ें',
      addReminder: '+ नया रिमाइंडर जोड़ें',
      saveNotes: 'नोट्स सुरक्षित करें',
      notesPlaceholder: 'डॉक्टर की सलाह, रक्तचाप विवरण या विशेष निर्देश यहाँ लिखें...',
    },
    en: {
      title: 'Caregiver Mode',
      pinTitle: 'Enter 4-digit Security PIN',
      pinSub: 'To protect family and clinical settings, please verify caregiver PIN.',
      defaultPinHint: 'Default PIN is 1 2 3 4',
      photosTab: 'Manage Photos',
      remindersTab: 'Reminders',
      notesTab: 'Care Notes',
      syncTab: 'Cloud Sync',
      exitBtn: 'Exit Caregiver Mode',
      addPhoto: '+ Add Memory Lane Photo',
      addReminder: '+ Add Voice / Schedule Reminder',
      saveNotes: 'Save Care Notes',
      notesPlaceholder: 'Clinical observations, dosage notes, or dietary preferences for family...',
    },
    brx: {
      title: 'हेफाजाबगिरि मोद',
      pinTitle: 'PIN अनजिमा हो',
      pinSub: 'नखर आरो देहानि बाथ्रा रैखा खालामनो ४ अनजिमानि पिन हो',
      defaultPinHint: 'पिन: 1 2 3 4',
      photosTab: 'सावगारि',
      remindersTab: 'गोसोखां होनाय',
      notesTab: 'देहा लिरनाय',
      syncTab: 'क्लाउड सिंक',
      exitBtn: 'ओंखारलां',
      addPhoto: '+ गोदान सावगारि',
      addReminder: '+ गोदान गोसोखां',
      saveNotes: 'लिरनाय दोन',
      notesPlaceholder: 'डाक्टरनि बिथोन बेयाव लिर...',
    },
    mni: {
      title: 'য়ুম্বুকপু শেন্নবগী মোদ',
      pinTitle: 'পিন (PIN) নম্বৰ চংবা',
      pinSub: 'ইমুংগী অমসুং হকশেলগী ৱাফম লৈনবা ৪-দিজিৎ পিন থম্মু',
      defaultPinHint: 'পিন: 1 2 3 4',
      photosTab: 'ফোতো',
      remindersTab: 'স্মারক',
      notesTab: 'হকশেলগী ইবশিং',
      syncTab: 'ক্লাউদ সিঙ্ক',
      exitBtn: 'মোদ থাদোকপা',
      addPhoto: '+ অনৌবা ফোতো হাপ্পা',
      addReminder: '+ অনৌবা স্মারক হাপ্পা',
      saveNotes: 'ইবা থমজিনবা',
      notesPlaceholder: 'দোক্তরগী পাউতাক মসিদা ইবিয়ু...',
    },
    lus: {
      title: 'Enkawltu Mode',
      pinTitle: 'Security PIN Chhu rawh',
      pinSub: 'Chhungkua leh damdawi lam thuruk vawn ṭhat nan 4-digit PIN chhu rawh.',
      defaultPinHint: 'PIN chu: 1 2 3 4',
      photosTab: 'Thlalak Enkawlna',
      remindersTab: 'Hriattirna',
      notesTab: 'Enkawlna Chhinchhiahna',
      syncTab: 'Cloud Sync',
      exitBtn: 'Enkawltu Mode Chhuahsan Rawh',
      addPhoto: '+ Thlalak Tharah Dah Rawh',
      addReminder: '+ Hriattirna Tharah Dah Rawh',
      saveNotes: 'Chhinchhiah Vawng Ṭha Rawh',
      notesPlaceholder: 'Doctor thurawn leh enkawlna dan te...',
    },
    kha: {
      title: 'Ka Mode Nongsmar',
      pinTitle: 'Thep ia u PIN',
      pinSub: 'Ban iada ia ka iing ka sem thep ia u 4-digit PIN.',
      defaultPinHint: 'U PIN: 1 2 3 4',
      photosTab: 'Ki Dur',
      remindersTab: 'Ki Jingkynmaw',
      notesTab: 'Ki Jingthoh',
      syncTab: 'Cloud Sync',
      exitBtn: 'Mih noh na ka Mode Nongsmar',
      addPhoto: '+ Pynrung Dur Thymmai',
      addReminder: '+ Pynrung Jingkynmaw',
      saveNotes: 'Kynshew',
      notesPlaceholder: 'Ki jingbthah doktor...',
    },
    grt: {
      title: 'Nitsangipa Mode',
      pinTitle: 'PIN-ko Seokbo',
      pinSub: 'Nokdang aro an·seng baljokani kamna 4-digit PIN-ko sebo.',
      defaultPinHint: 'PIN: 1 2 3 4',
      photosTab: 'Noksa',
      remindersTab: 'Gual·atani',
      notesTab: 'Sea-Jotani',
      syncTab: 'Cloud Sync',
      exitBtn: 'Moko Watbo',
      addPhoto: '+ Noksa Gital',
      addReminder: '+ Gual·atani Gital',
      saveNotes: 'Rakkibo',
      notesPlaceholder: 'Doctorni kattarang...',
    },
    trp: {
      title: 'Naisa Nai Mode',
      pinTitle: 'PIN Suidi',
      pinSub: 'Nok tei bwsari ni bagwi 4-digit PIN suidi.',
      defaultPinHint: 'PIN: 1 2 3 4',
      photosTab: 'Photo',
      remindersTab: 'Kok',
      notesTab: 'Swimanok',
      syncTab: 'Cloud Sync',
      exitBtn: 'Ongkhorna',
      addPhoto: '+ Kwtal Photo',
      addReminder: '+ Kwtal Kok',
      saveNotes: 'Rakhi',
      notesPlaceholder: 'Doctor ni kok...',
    },
    nag: {
      title: 'Caregiver Mode',
      pinTitle: 'Security PIN Dilibi',
      pinSub: 'Ghor manu aru health secure rakhikena 4-digit PIN dilibi.',
      defaultPinHint: 'Default PIN: 1 2 3 4',
      photosTab: 'Photo Manage',
      remindersTab: 'Reminder',
      notesTab: 'Health Notes',
      syncTab: 'Cloud Sync',
      exitBtn: 'Caregiver Mode Ula',
      addPhoto: '+ Naya Photo Lagabi',
      addReminder: '+ Naya Reminder Lagabi',
      saveNotes: 'Notes Save Koribi',
      notesPlaceholder: 'Doctor laga advice, medicine notes...',
    },
    ne: {
      title: 'हेरचाहकर्ता मोड',
      pinTitle: 'सुरक्षा पिन (PIN) हाल्नुहोस्',
      pinSub: 'पारिवारिक तथा स्वास्थ्य विवरण सुरक्षित राख्न ४-अङ्कको पिन हाल्नुहोस्।',
      defaultPinHint: 'पूर्वनिर्धारित पिन: 1 2 3 4',
      photosTab: 'तस्बिरहरू',
      remindersTab: 'रिमाइन्डरहरू',
      notesTab: 'स्वास्थ्य टिपोट',
      syncTab: 'क्लाउड सिङ्क',
      exitBtn: 'हेरचाहकर्ता मोडबाट बाहिरिनुहोस्',
      addPhoto: '+ नयाँ तस्बिर थप्नुहोस्',
      addReminder: '+ नयाँ रिमाइन्डर थप्नुहोस्',
      saveNotes: 'टिपोट सुरक्षित गर्नुहोस्',
      notesPlaceholder: 'चिकित्सकको सल्लाह, औषधिको विवरण यहाँ लेख्नुहोस्...',
    },
  };

  return dict[lang] || dict.en;
};

export const getSpeakSmritiStrings = (lang: LanguageCode) => {
  const dict: Record<LanguageCode, {
    modalTitle: string;
    companionName: string;
    listening: string;
    speaking: string;
    thinking: string;
    tapToSpeak: string;
    tapToStop: string;
    inputPlaceholder: string;
    suggestedTopics: string;
    suggestions: string[];
    replayVoice: string;
  }> = {
    as: {
      modalTitle: 'স্মৃতিৰ সৈতে কথা পাতক',
      companionName: 'স্মৃতি — আপোনাৰ মৰমৰ সংগী',
      listening: 'আপোনাৰ কথা শুনা হৈছে... মনৰ কথা কওক',
      speaking: 'স্মৃতিয়ে কৈ আছে...',
      thinking: 'স্মৃতিয়ে উত্তৰ সাজু কৰিছে...',
      tapToSpeak: 'কথা ক’বলৈ মাইক্ৰ’ফোনত টিপক',
      tapToStop: 'কৈ শেষ হ’লে টিপক',
      inputPlaceholder: 'আপোনাৰ কথা লিখক বা মাইক টিপক...',
      suggestedTopics: 'প্ৰস্তাৱিত বিষয়সমূহ',
      suggestions: ['আজি দিনটো কেনে যাব?', 'মোক এটা ধুনীয়া সাধু কওক', 'মোৰ পৰিয়ালৰ বিষয়ে কওক'],
      replayVoice: 'পুনৰ শুনক',
    },
    hi: {
      modalTitle: 'स्मृति से बात करें',
      companionName: 'स्मृति — आपकी प्यारी साथी',
      listening: 'आपकी बात ध्यान से सुन रहे हैं... बेझिझक बोलें',
      speaking: 'स्मृति बोल रही है...',
      thinking: 'स्मृति सोच रही है...',
      tapToSpeak: 'बात करने के लिए माइक दबाएँ',
      tapToStop: 'रोकने के लिए दबाएँ',
      inputPlaceholder: 'यहाँ लिखें या माइक दबाकर बोलें...',
      suggestedTopics: 'सुझाए गए विषय',
      suggestions: ['आज का दिन कैसा रहेगा?', 'मुझे एक सुंदर कहानी सुनाओ', 'मेरे परिवार के बारे में बताओ'],
      replayVoice: 'फिर से सुनें',
    },
    en: {
      modalTitle: 'Speak with Smriti',
      companionName: 'Smriti — Caring AI Companion',
      listening: 'Listening to you... speak freely',
      speaking: 'Smriti is speaking...',
      thinking: 'Smriti is thinking...',
      tapToSpeak: 'Tap microphone to speak',
      tapToStop: 'Tap to finish speaking',
      inputPlaceholder: 'Type a message or tap microphone...',
      suggestedTopics: 'Suggested Topics',
      suggestions: ['How is the weather today?', 'Tell me an inspiring story', 'Tell me about my family'],
      replayVoice: 'Replay voice',
    },
    brx: {
      modalTitle: 'स्मृतीजों रायलाय',
      companionName: 'स्मृती — लोगो',
      listening: 'खोनासंन्दों... बाथ्रा बुं',
      speaking: 'स्मृतीया बुंदों...',
      thinking: 'स्मृतीया सानदों...',
      tapToSpeak: 'माइक थुना बुं',
      tapToStop: 'दोन',
      inputPlaceholder: 'लिर एबा माइक थु...',
      suggestedTopics: 'बाथ्राफोर',
      suggestions: ['दिनै मा जागोन?', 'मोनसे सल’ खोन्था', 'नखरनि खोथा बुं'],
      replayVoice: 'फिन खोनासं',
    },
    mni: {
      modalTitle: 'স্মৃতিগা ৱারী শানৌ',
      companionName: 'স্মৃতি — মরুপ',
      listening: 'অদোমগী ৱারী তারি... হায়বীয়ু',
      speaking: 'স্মৃতিনা ঙাংলি...',
      thinking: 'স্মৃতিনা খল্লি...',
      tapToSpeak: 'মাইক নমদুনা ঙাংউ',
      tapToStop: 'লেপহল্লু',
      inputPlaceholder: 'ইবীয়ু নত্রগা মাইক নম্মু...',
      suggestedTopics: 'ৱাফমশিং',
      suggestions: ['ঙসি করম তৌগনি?', 'ৱারী অমা তাশিনবিয়ু', 'ইমুংগী মতাংদা হায়বীয়ু'],
      replayVoice: 'অমুক তাউ',
    },
    lus: {
      modalTitle: 'Smriti Be Rawh',
      companionName: 'Smriti — Ṭhian Ṭha',
      listening: 'I sawi ngun takin kan ngaithla e...',
      speaking: 'Smriti a ṭawng mek...',
      thinking: 'Smriti a inngaihtuah mek...',
      tapToSpeak: 'Mic hmet la ṭawng rawh',
      tapToStop: 'Tawp tir rawh',
      inputPlaceholder: 'I duhzawng ziak la...',
      suggestedTopics: 'Sawi duh thlan tur',
      suggestions: ['Vawiin boruak a ṭha em?', 'Thawnthu mawi tak min hrilh teh', 'Ka chhungte chanchin min hrilh teh'],
      replayVoice: 'Ngaithla nawn rawh',
    },
    kha: {
      modalTitle: 'Kren bad ka Smriti',
      companionName: 'Smriti — Paralok',
      listening: 'Dang sngap... kren beit',
      speaking: 'Ka Smriti ka kren...',
      thinking: 'Ka Smriti ka pyrkhat...',
      tapToSpeak: 'Tep mic ban kren',
      tapToStop: 'Tep ban sangeh',
      inputPlaceholder: 'Thoh lane tep mic...',
      suggestedTopics: 'Ki Phang',
      suggestions: ['Kumno ka sngi mynta?', 'Iathuh khana ia nga', 'Iathuh shaphang ka iing'],
      replayVoice: 'Sngap biang',
    },
    grt: {
      modalTitle: 'Smritiko Aganbo',
      companionName: 'Smriti — Rorim·gipa',
      listening: 'Knatimenga... aganbo',
      speaking: 'Smriti aganenga...',
      thinking: 'Smriti chanchia...',
      tapToSpeak: 'Mic-ko thike aganbo',
      tapToStop: 'Dondikbo',
      inputPlaceholder: 'Sebo ba mic-ko thikbo...',
      suggestedTopics: 'Golponi Katta',
      suggestions: ['Da·al sal maikai?', 'Golpo aganbo', 'Nokdangni gimin aganbo'],
      replayVoice: 'Knataibo',
    },
    trp: {
      modalTitle: 'Smriti bai Kok Saldi',
      companionName: 'Smriti — Yaguk',
      listening: 'Khna twng... kok sa',
      speaking: 'Smriti kok sa tong...',
      thinking: 'Smriti chanchi tong...',
      tapToSpeak: 'Mic tekdi tei sa',
      tapToStop: 'Don-di',
      inputPlaceholder: 'Suidi ba mic tekdi...',
      suggestedTopics: 'Kokni Bag',
      suggestions: ['Tini sal khorok?', 'Kotha saidi', 'Nok ni kotha saidi'],
      replayVoice: 'Uaisa khna',
    },
    nag: {
      modalTitle: 'Smriti logot Kotha Koribi',
      companionName: 'Smriti — Sathi',
      listening: 'Suni ase... kotha koribi',
      speaking: 'Smriti kotha kori ase...',
      thinking: 'Smriti bhabi ase...',
      tapToSpeak: 'Mic dababi kotha koribi',
      tapToStop: 'Bondho koribi',
      inputPlaceholder: 'Likhidi naile mic dababi...',
      suggestedTopics: 'Suggested Topics',
      suggestions: ['Aji din kasto thakibo?', 'Etu sundor kotha sunabi', 'Mora ghor manu kotha kobi'],
      replayVoice: 'Aru sunibi',
    },
    ne: {
      modalTitle: 'स्मृतिसँग कुरा गर्नुहोस्',
      companionName: 'स्मृति — मायालु साथी',
      listening: 'हजुरको कुरा सुन्दैछ... मनको कुरा बोल्नुहोस्',
      speaking: 'स्मृति बोल्दैछिन्...',
      thinking: 'स्मृति विचार गर्दैछिन्...',
      tapToSpeak: 'बोल्नको लागि माइक थिच्नुहोस्',
      tapToStop: 'बोली सकेपछि रोक्नुहोस्',
      inputPlaceholder: 'यहाँ सन्देश लेख्नुहोस् वा माइक थिच्नुहोस्...',
      suggestedTopics: 'सुझाएका विषयहरू',
      suggestions: ['आजको दिन कस्तो रहनेछ?', 'मलाई एउटा मिठो कथा सुनाउनुहोस्', 'मेरो परिवारको बारेमा भन्नुहोस्'],
      replayVoice: 'फेरि सुन्नुहोस्',
    },
  };

  return dict[lang] || dict.en;
};

export const getHeaderNotificationStrings = (lang: LanguageCode) => {
  const dict: Record<LanguageCode, {
    notificationsTitle: string;
    liveSynced: string;
    item1Title: string;
    item1Desc: string;
    item2Title: string;
    item2Desc: string;
    dismiss: string;
  }> = {
    as: {
      notificationsTitle: 'স্মৃতি জাননীসমূহ',
      liveSynced: 'পৰিয়ালৰ সৈতে সক্ৰিয়ভাৱে সংযুক্ত',
      item1Title: 'সেৱা চক্ৰৰ আপডেট',
      item1Desc: 'প্ৰিয়াই পুৱাৰ নিয়মীয়া স্বাস্থ্য পৰীক্ষাৰ সময়সূচী তৈয়াৰ কৰিছে।',
      item2Title: 'অৰ্জুনৰ পৰা বাৰ্তা',
      item2Desc: 'আপোনাৰ স্মৃতি পথত এখন নতুন ধুনীয়া ছবি পঠোৱা হৈছে।',
      dismiss: 'সকলো জাননী পঢ়া হ’ল',
    },
    hi: {
      notificationsTitle: 'स्मृति सूचनाएँ',
      liveSynced: 'परिवार के साथ सक्रिय रूप से कनेक्टेड',
      item1Title: 'केयर सर्कल अपडेट',
      item1Desc: 'प्रिया ने सुबह की स्वास्थ्य जांच का समय निर्धारित किया है।',
      item2Title: 'अर्जुन का संदेश',
      item2Desc: 'आपकी मेमोरी लेन में एक नई सुंदर फ़ोटो जोड़ी गई है।',
      dismiss: 'सभी सूचनाएँ पढ़ ली गईं',
    },
    en: {
      notificationsTitle: 'Notifications & Updates',
      liveSynced: 'Live Synced with Family',
      item1Title: 'Care Circle update',
      item1Desc: 'Priya scheduled a gentle morning routine check.',
      item2Title: 'Message from Arjun',
      item2Desc: 'Thinking of you! Sent a new photo to your Memory Lane.',
      dismiss: 'Dismiss',
    },
    brx: {
      notificationsTitle: 'मिथिहोनायफोर',
      liveSynced: 'नखरजों गोरोबनाय',
      item1Title: 'हेफाजाब सर्कल',
      item1Desc: 'प्रियाया फुंनि देहा नायनायनि सोदोब खालामबाय।',
      item2Title: 'अर्जुननिफ्राय बाथ्रा',
      item2Desc: 'नोंथांनि सावगारि बिफाङाव गोदान सावगारि हरबाय।',
      dismiss: 'गासैबो फरायबाय',
    },
    mni: {
      notificationsTitle: 'পাউ পাউচেংশিং',
      liveSynced: 'ইমুংগা পুনশিনবা',
      item1Title: 'শেন্নবা কাংলুপ পাউ',
      item1Desc: 'প্রিয়ানা অয়ুক্কী হকশেল য়েংশিনবা শেম্লে।',
      item2Title: 'অর্জুনদগী পাউ',
      item2Desc: 'অদোমগী মেমোরি লেন্দা অনৌবা ফোতো থারক্লে।',
      dismiss: 'লোইনা পাম্লে',
    },
    lus: {
      notificationsTitle: 'Hriattirnate',
      liveSynced: 'Chhungkua nen thlunzawm a ni',
      item1Title: 'Enkawltu Hriattirna',
      item1Desc: 'Priya-in zing lam in check-up a siam sak che.',
      item2Title: 'Arjun hnen aṭangin',
      item2Desc: 'Thlalak thar Memory Lane-ah a rawn dah e.',
      dismiss: 'Titawp rawh',
    },
    kha: {
      notificationsTitle: 'Ki Jingpyntip',
      liveSynced: 'La iateh bad ka iing',
      item1Title: 'Jingpyntip Nongsmar',
      item1Desc: 'Ka Priya ka la buh por peit koit dah step.',
      item2Title: 'Ktien na u Arjun',
      item2Desc: 'Dur thymmai ha Memory Lane.',
      dismiss: 'Pynkut',
    },
    grt: {
      notificationsTitle: 'U·iatani',
      liveSynced: 'Nokdang baksa nangrima',
      item1Title: 'Nitsangipa Update',
      item1Desc: 'Priya pringo an·seng baljokko nina thik ka·aha.',
      item2Title: 'Arjunni Katta',
      item2Desc: 'Memory Lane-o noksa gitalko watataha.',
      dismiss: 'Gimikko watbo',
    },
    trp: {
      notificationsTitle: 'Kokthum',
      liveSynced: 'Nok bai buma tong',
      item1Title: 'Naisa Nai Kok',
      item1Desc: 'Priya phung bwsari naina bagwi thik khlaikha.',
      item2Title: 'Arjun ni Kok',
      item2Desc: 'Memory Lane o kwtal photo phaikha.',
      dismiss: 'Bebak paikhak',
    },
    nag: {
      notificationsTitle: 'Notifications',
      liveSynced: 'Family logot connect ase',
      item1Title: 'Care Circle update',
      item1Desc: 'Priya sokal check-up laga time banaishey.',
      item2Title: 'Arjun laga message',
      item2Desc: 'Memory Lane te naya photo pathaishey.',
      dismiss: 'Dismiss',
    },
    ne: {
      notificationsTitle: 'सूचनाहरू',
      liveSynced: 'परिवारसँग प्रत्यक्ष जोडिएको',
      item1Title: 'हेरचाह समूह जानकारी',
      item1Desc: 'प्रियाले बिहानको स्वास्थ्य जाँच तालिका मिलाइन्।',
      item2Title: 'अर्जुनको सन्देश',
      item2Desc: 'मेमोरी लेनमा एउटा नयाँ तस्बिर थपिएको छ।',
      dismiss: 'सबै हटाइयो',
    },
  };

  return dict[lang] || dict.en;
};
