import { LanguageCode } from '../types';

export const getVoiceReminderModalStrings = (lang: LanguageCode) => {
  const dict: Record<LanguageCode, {
    modalTitle: string;
    recordTitle: string;
    recordingActiveTitle: string;
    recordSub: string;
    recordingActiveSub: string;
    btnRecord: string;
    btnStop: string;
    listeningHint: string;
    tapStartHint: string;
    timePickerTitle: string;
    timePickerSub: string;
    voiceNoteBadge: string;
    recordedSuffix: string;
    rerecord: string;
    quickSchedule: string;
    selectExactTime: string;
    today: string;
    tomorrow: string;
    pastTimeError: string;
    switchToTomorrow: string;
    saveButton: string;
    minShort: string;
    hourShort: string;
  }> = {
    as: {
      modalTitle: 'কণ্ঠস্বৰ স্মাৰক',
      recordTitle: 'আপোনাৰ কণ্ঠস্বৰত স্মাৰক ৰেকৰ্ড কৰক',
      recordingActiveTitle: 'কণ্ঠস্বৰ ৰেকৰ্ড হৈ আছে...',
      recordSub: 'তলৰ বুটামটো টিপি মনত পেলাবলগীয়া কথাটো কওক। সেই সময়ত আপোনাৰ কণ্ঠস্বৰতে বাজি উঠিব!',
      recordingActiveSub: 'স্পষ্টকৈ কওক। শেষ হ’লে বন্ধ কৰক বুটাম টিপক।',
      btnRecord: 'ৰেকৰ্ড',
      btnStop: 'বন্ধ কৰক',
      listeningHint: 'শুনা হৈছে... শেষ হ’লে টিপক',
      tapStartHint: 'ৰেকৰ্ড কৰিবলৈ টিপক',
      timePickerTitle: 'এইটো কোন সময়ত বাজিব লাগে?',
      timePickerSub: 'নিৰ্ধাৰিত সময়ত আপোনাৰ কণ্ঠস্বৰৰ স্মাৰকটি নিজে নিজে বাজি উঠিব।',
      voiceNoteBadge: 'আপোনাৰ কণ্ঠস্বৰ বাৰ্তা',
      recordedSuffix: 'ছেকেণ্ড ৰেকৰ্ড হ’ল',
      rerecord: 'পুনৰ ৰেকৰ্ড',
      quickSchedule: 'দ্ৰুত সময় নিৰ্ধাৰণ:',
      selectExactTime: 'সঠিক সময় বাছক:',
      today: 'আজি',
      tomorrow: 'কাইলৈ',
      pastTimeError: 'অনুগ্ৰহ কৰি আহিবলগীয়া ভৱিষ্যতৰ সময় বাছক বা কাইলৈৰ বাবে নিৰ্ধাৰণ কৰক।',
      switchToTomorrow: 'কাইলৈ নিৰ্ধাৰণ কৰিবলৈ ইয়াত টিপক',
      saveButton: 'কণ্ঠস্বৰ স্মাৰক সংৰক্ষণ কৰক',
      minShort: 'মিনিট',
      hourShort: 'ঘণ্টা',
    },
    hi: {
      modalTitle: 'वॉयस रिमाइंडर',
      recordTitle: 'अपनी आवाज़ में रिमाइंडर रिकॉर्ड करें',
      recordingActiveTitle: 'आवाज़ रिकॉर्ड हो रही है...',
      recordSub: 'नीचे दिया बटन दबाकर अपना रिमाइंडर बोलें। यह आपकी अपनी आवाज़ में बजेगा!',
      recordingActiveSub: 'स्पष्ट बोलें। पूरा होने पर स्टॉप बटन दबाएँ।',
      btnRecord: 'रिकॉर्ड',
      btnStop: 'रोकें',
      listeningHint: 'सुन रहे हैं... रोकने के लिए टैप करें',
      tapStartHint: 'रिकॉर्डिंग शुरू करने के लिए टैप करें',
      timePickerTitle: 'यह रिमाइंडर किस समय बजना चाहिए?',
      timePickerSub: 'तय समय पर आपका रिकॉर्ड किया संदेश अपने आप बज उठेगा।',
      voiceNoteBadge: 'आपका वॉयस नोट',
      recordedSuffix: 'सेकंड रिकॉर्ड हुआ',
      rerecord: 'फिर से रिकॉर्ड करें',
      quickSchedule: 'त्वरित समय चयन:',
      selectExactTime: 'सटीक समय चुनें:',
      today: 'आज',
      tomorrow: 'कल',
      pastTimeError: 'कृपया आने वाला समय चुनें या कल का चयन करें।',
      switchToTomorrow: 'कल के लिए सेट करने के लिए यहाँ दबाएँ',
      saveButton: 'वॉयस रिमाइंडर सेव करें',
      minShort: 'मिनट',
      hourShort: 'घंटा',
    },
    en: {
      modalTitle: 'Voice Reminder',
      recordTitle: 'Record Voice Reminder',
      recordingActiveTitle: 'Recording your voice...',
      recordSub: 'Tap the button below and speak your reminder. It will play back in your own voice!',
      recordingActiveSub: 'Speak clearly into your microphone. Tap stop when finished.',
      btnRecord: 'Record',
      btnStop: 'Stop',
      listeningHint: 'Listening... Tap to stop',
      tapStartHint: 'Tap to start recording',
      timePickerTitle: 'What time should this play?',
      timePickerSub: 'Your original voice note will play automatically at this time.',
      voiceNoteBadge: 'Your Voice Note',
      recordedSuffix: 's recorded',
      rerecord: 'Re-record',
      quickSchedule: 'Quick Schedule:',
      selectExactTime: 'Select Exact Time:',
      today: 'Today',
      tomorrow: 'Tomorrow',
      pastTimeError: 'Please choose a future time or select tomorrow.',
      switchToTomorrow: 'Click here to schedule for tomorrow instead',
      saveButton: 'Save Voice Reminder',
      minShort: 'min',
      hourShort: 'hour',
    },
    brx: {
      modalTitle: 'गोसोखां होनाय',
      recordTitle: 'गावनि गांरावजों गोसोखां रेकर्ड खालाम',
      recordingActiveTitle: 'गांराव रेकर्ड जाबाय...',
      recordSub: 'गाहायाव थुनानै बुं। बेयो नोंथांनि रावजोंनो बाजायगोन!',
      recordingActiveSub: 'गोजां बुं, जोबबा बन्द खालाम।',
      btnRecord: 'रेकर्ड',
      btnStop: 'दोन',
      listeningHint: 'खोनासंन्दों... दोननो थु',
      tapStartHint: 'रेकर्ड खालामनो थु',
      timePickerTitle: 'बेयो मा समाव बाजायगोन?',
      timePickerSub: 'बे समाव नोंथांनि गांरावा गावनो गाव बाजायगोन।',
      voiceNoteBadge: 'गांराव',
      recordedSuffix: 'सेकेन्ड',
      rerecord: 'फिन रेकर्ड',
      quickSchedule: 'सम सायख’:',
      selectExactTime: 'थार सम सायख’:',
      today: 'दिनै',
      tomorrow: 'गाबोन',
      pastTimeError: 'इयुननि सम सायख’ एबा गाबोन दोन।',
      switchToTomorrow: 'गाबोननि थाखाय बेयाव थु',
      saveButton: 'गोसोखां दोन',
      minShort: 'मिनिट',
      hourShort: 'घन्टा',
    },
    mni: {
      modalTitle: 'খোঞ্জেলগী স্মারক',
      recordTitle: 'অদোমগী খোঞ্জেলদা স্মারক রেকোৰ্দ তৌবীয়ু',
      recordingActiveTitle: 'খোঞ্জেল রেকোৰ্দ তৌরি...',
      recordSub: 'মখাগী বোতাম অদু নমদুনা হায়বীয়ু। মসিনা অদোমগী খোঞ্জেলদা তাগনি!',
      recordingActiveSub: 'ময়েক শেংনা হায়বীয়ু। লোইবদা লেপহল্লু।',
      btnRecord: 'রেকোৰ্দ',
      btnStop: 'লেপহল্লু',
      listeningHint: 'তারি... লেপহন্নবা নম্মু',
      tapStartHint: 'রেকোৰ্দ হৌনবা নম্মু',
      timePickerTitle: 'মসি মতম করম্বদা তাগদগে?',
      timePickerSub: 'মতৌ অসিদা অদোমগী খোঞ্জেল অদু মশানা মশা লাউথোক্কনি।',
      voiceNoteBadge: 'অদোমগী খোঞ্জেল',
      recordedSuffix: 'সেকেন্ড',
      rerecord: 'অমুক হন্না তৌবা',
      quickSchedule: 'মতম খল্লু:',
      selectExactTime: 'অচুম্বা মতম খল্লু:',
      today: 'ঙসি',
      tomorrow: 'হয়েং',
      pastTimeError: 'চানবীদুনা লাক্কদবা মতম খল্লু নত্রগা হয়েং খল্লু।',
      switchToTomorrow: 'হয়েংগীদমক মসিদা নম্মু',
      saveButton: 'স্মারক থমজিনবা',
      minShort: 'মিনিট',
      hourShort: 'পুং',
    },
    lus: {
      modalTitle: 'Aw Hriattirna',
      recordTitle: 'I aw ngeiin hriattirna siam rawh',
      recordingActiveTitle: 'I aw record mek a ni...',
      recordSub: 'Hnuai ami hi hmet la i sawi duh sawi rawh.',
      recordingActiveSub: 'Fiah takin sawi la, a tawpah hmet leh rawh.',
      btnRecord: 'Record',
      btnStop: 'Tawp tir',
      listeningHint: 'Ngaithla mek... tawp tir rawh',
      tapStartHint: 'Record tan nan hmet rawh',
      timePickerTitle: 'Eng hunah nge a rik ang?',
      timePickerSub: 'He huna hian i aw ngei kha a rawn ri chhuak ang.',
      voiceNoteBadge: 'I aw note',
      recordedSuffix: 'secs record a ni',
      rerecord: 'Record nawn rawh',
      quickSchedule: 'Hun rang thlan:',
      selectExactTime: 'Hun dik thlang rawh:',
      today: 'Vawiin',
      tomorrow: 'Naktuk',
      pastTimeError: 'Hun la thleng lo zawk thlang rawh.',
      switchToTomorrow: 'Naktuk atan heta hi hmet rawh',
      saveButton: 'Hriattirna Vawng Ṭha Rawh',
      minShort: 'mins',
      hourShort: 'hrs',
    },
    kha: {
      modalTitle: 'Jingkynmaw da ka Ktien',
      recordTitle: 'Record ia ka Ktien ban Kynmaw',
      recordingActiveTitle: 'Dang record...',
      recordSub: 'Tep ia u button bad kren. Kan riew da ka ktien jong phi!',
      recordingActiveSub: 'Kren shai, tep haba la kut.',
      btnRecord: 'Record',
      btnStop: 'Sangeh',
      listeningHint: 'Dang sngap... tep ban sangeh',
      tapStartHint: 'Tep ban record',
      timePickerTitle: 'Kano ka por kan riew?',
      timePickerSub: 'Kan riew beit ha katei ka por.',
      voiceNoteBadge: 'Ka Sur Ktien',
      recordedSuffix: 's',
      rerecord: 'Record biang',
      quickSchedule: 'Jied Por kloi:',
      selectExactTime: 'Jied Por shai:',
      today: 'Mynta ka sngi',
      tomorrow: 'Lashai',
      pastTimeError: 'Jied ia ka por kaba dang sah.',
      switchToTomorrow: 'Tep hangne na ka bynta lashai',
      saveButton: 'Kynshew Jingkynmaw',
      minShort: 'min',
      hourShort: 'kynta',
    },
    grt: {
      modalTitle: 'Ku·rangchi Gual·atani',
      recordTitle: 'Nang·ni ku·rangko record ka·bo',
      recordingActiveTitle: 'Ku·rangko record ka·enga...',
      recordSub: 'Buttonko thikbo aro aganbo. Nang·ni ku·rango ring·gnok!',
      recordingActiveSub: 'Tale aganbo, machotode dondikbo.',
      btnRecord: 'Record',
      btnStop: 'Dondikbo',
      listeningHint: 'Knatimenga... thike dondikbo',
      tapStartHint: 'Record ka·na thikbo',
      timePickerTitle: 'Bano ring·gen?',
      timePickerSub: 'Ia somoio nang·ni ku·rang bansrang ring·gen.',
      voiceNoteBadge: 'Ku·rang Note',
      recordedSuffix: 's record ka·aha',
      rerecord: 'Record taibo',
      quickSchedule: 'Somoiko Bakan Seokbo:',
      selectExactTime: 'Kakket Somoi:',
      today: 'Da·al',
      tomorrow: 'Gnapin',
      pastTimeError: 'Re·anggimin somoiko donga.',
      switchToTomorrow: 'Gnapinna seokna iano thikbo',
      saveButton: 'Gual·ataniko Rakkibo',
      minShort: 'min',
      hourShort: 'khorok',
    },
    trp: {
      modalTitle: 'Khuk bai Kok',
      recordTitle: 'Nini khuk bai record khlai',
      recordingActiveTitle: 'Record khlai tong...',
      recordSub: 'Button tekdi tei sa. Nini khuk bai khna phano!',
      recordingActiveSub: 'Kaham khlaike sa, paiba don-di.',
      btnRecord: 'Record',
      btnStop: 'Don-di',
      listeningHint: 'Khnatong... tekdi don-na',
      tapStartHint: 'Record khlai-na tekdi',
      timePickerTitle: 'Tamor jora o ring nai?',
      timePickerSub: 'A jorao nini kok khna nai.',
      voiceNoteBadge: 'Kok Note',
      recordedSuffix: 's',
      rerecord: 'Uaisa Record',
      quickSchedule: 'Jora Kwtal:',
      selectExactTime: 'Jora Kaham:',
      today: 'Tini',
      tomorrow: 'Khabang',
      pastTimeError: 'Khorok jora chongdi.',
      switchToTomorrow: 'Khabang ni bagwi tekdi',
      saveButton: 'Kok Rakhi',
      minShort: 'min',
      hourShort: 'jora',
    },
    nag: {
      modalTitle: 'Voice Reminder',
      recordTitle: 'Nijor Awaz te Reminder Record Koribi',
      recordingActiveTitle: 'Awaz record kori ase...',
      recordSub: 'Tole button dababi aru kotha kobi. Nijor awaz te baji uthibo!',
      recordingActiveSub: 'Clear pora kobi, sesh hole stop dababi.',
      btnRecord: 'Record',
      btnStop: 'Stop',
      listeningHint: 'Suni ase... bondho koribole dababi',
      tapStartHint: 'Record shuru koribole dababi',
      timePickerTitle: 'Konta time te bajibo lage?',
      timePickerSub: 'Etu time te nijor awaz automatic baji uthibo.',
      voiceNoteBadge: 'Nijor Voice Note',
      recordedSuffix: 's record hoishey',
      rerecord: 'Aru Record Koribi',
      quickSchedule: 'Joldi Time Select:',
      selectExactTime: 'Exact Time Select:',
      today: 'Aji',
      tomorrow: 'Kali',
      pastTimeError: 'Ahebole thaka time ba kali select koribi.',
      switchToTomorrow: 'Kali nimite set koribole etey dababi',
      saveButton: 'Voice Reminder Save Koribi',
      minShort: 'min',
      hourShort: 'ghonta',
    },
    ne: {
      modalTitle: 'आवाज रिमाइन्डर',
      recordTitle: 'आफ्नै आवाजमा रिमाइन्डर रेकर्ड गर्नुहोस्',
      recordingActiveTitle: 'आवाज रेकर्ड भइरहेको छ...',
      recordSub: 'तलको बटन थिचेर रिमाइन्डर बोल्नुहोस्। यो आफ्नै आवाजमा बज्नेछ!',
      recordingActiveSub: 'स्पष्टसँग बोल्नुहोस्। सकिएपछि रोक्नुहोस् थिच्नुहोस्।',
      btnRecord: 'रेकर्ड',
      btnStop: 'रोक्नुहोस्',
      listeningHint: 'सुन्दैछ... रोक्न थिच्नुहोस्',
      tapStartHint: 'रेकर्ड सुरु गर्न थिच्नुहोस्',
      timePickerTitle: 'यो कुन समयमा बज्नु पर्छ?',
      timePickerSub: 'तोकिएको समयमा हजुरको रेकर्ड गरिएको आवाज आफैँ बज्नेछ।',
      voiceNoteBadge: 'हजुरको आवाज',
      recordedSuffix: 'सेकेन्ड रेकर्ड भयो',
      rerecord: 'फेरि रेकर्ड गर्नुहोस्',
      quickSchedule: 'छिटो समय चयन:',
      selectExactTime: 'सटीक समय छान्नुहोस्:',
      today: 'आज',
      tomorrow: 'भोलि',
      pastTimeError: 'कृपया आउने समय वा भोलिको समय छान्नुहोस्।',
      switchToTomorrow: 'भोलिको लागि यहाँ थिच्नुहोस्',
      saveButton: 'आवाज रिमाइन्डर सुरक्षित गर्नुहोस्',
      minShort: 'मिनेट',
      hourShort: 'घण्टा',
    },
  };

  return dict[lang] || dict.en;
};
